# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Python runtime as a parent image
FROM python:3.12-slim-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install the package dependencies
RUN pip install --no-cache-dir setuptools wheel && \
    pip install --no-cache-dir .

# Environment variables for OpenAPI server
ENV OPENAPI_SPEC_URL=""
ENV API_AUTH_BEARER=""
ENV TOOL_WHITELIST=""
ENV TOOL_NAME_PREFIX=""
ENV OPENAPI_SIMPLE_MODE=false

# Make port 80 available to the world outside this container
EXPOSE 80

# Run mcp-openapi-proxy when the container launches
CMD ["uvx", "--from", "git+https://github.com/matthewhand/mcp-openapi-proxy", "mcp-openapi-proxy"]
